aliases:
    fleeks: cd ~/.local/share/fleek
    latest-fleek-version: nix run https://getfleek.dev/latest.tar.gz -- version
    please: sudo
    ssh-agent-man: echo \"THEY'VE GIVEN YOU A NUMBER\" && eval `ssh-agent -s` ssh-add && echo \"AND TAKEN AWAY YOUR NAME\"
    update-fleek: nix run https://getfleek.dev/latest.tar.gz -- update
allow_broken: false
auto_gc: true
bling: high
blocklist: []
byo_git: false
ejected: false
flakedir: .local/share/fleek
git:
    autocommit: true
    autopull: true
    autopush: true
    enabled: true
min_version: 0.8.4
name: taco on fleek
overlays: {}
packages:
    - asciiquarium
    - dog
    - du-dust
    - glances
    - gping
    - helix
    - hexyl
    - httpie
    - hyperfine
    - iotop
    - jq
    - lazygit
    - lsd
    - neofetch
    - neovim
    - nnn
    - oh-my-zsh
    - onefetch
    - oneko
    - pinentry-curses
    - pls
    - ripgrep
    - shellcheck
    - sl
    - thefuck
    - tldr
    - tmatrix
    - volta
    - xplr
paths:
    - $HOME/bin
    - $HOME/.local/bin
programs:
    - dircolors
shell: zsh
systems:
    - arch: x86_64
      home: ""
      hostname: myna
      os: linux
      user:
        email: daniel@tacowolf.net
        name: taco
        ssh_private_key_file: ~/.ssh/id_ed25519
        ssh_public_key_file: ~/.ssh/id_ed25519.pub
        username: taco
      username: taco
    - arch: x86_64
      home: ""
      hostname: fishcrow
      os: linux
      user:
        email: daniel@tacowolf.net
        name: taco
        ssh_private_key_file: ~/.ssh/id_ed25519
        ssh_public_key_file: ~/.ssh/id_ed25519.pub
        username: taco
      username: taco
track: nixos-unstable
unfree: true
users: []
